// Comprehensive predefined dataset of food items for restaurant owners/merchants.
// Grouped into distinct categories with recommended pricing, category tags & descriptions.

export const FOOD_CATALOG = [
  {
    group: "Tiffin & Breakfast",
    items: [
      {
        name: "Masala Dosa",
        category: "Meals",
        originalPrice: 120,
        discountPrice: 60,
        description: "Crispy golden crepe filled with spiced potato masala, served with coconut chutney & sambar.",
      },
      {
        name: "Plain Dosa",
        category: "Meals",
        originalPrice: 80,
        discountPrice: 40,
        description: "Classic crispy South Indian rice crepe served with coconut chutney & sambar.",
      },
      {
        name: "Ghee Roast Dosa",
        category: "Meals",
        originalPrice: 140,
        discountPrice: 70,
        description: "Golden crispy crepe roasted in pure ghee, served with fresh coconut chutney.",
      },
      {
        name: "Onion Dosa",
        category: "Meals",
        originalPrice: 110,
        discountPrice: 55,
        description: "Thin crispy crepe topped with finely chopped onions & green chillies.",
      },
      {
        name: "Rava Dosa",
        category: "Meals",
        originalPrice: 120,
        discountPrice: 60,
        description: "Lacy & crispy semolina crepe sprinkled with black pepper & cumin.",
      },
      {
        name: "Set Dosa",
        category: "Meals",
        originalPrice: 100,
        discountPrice: 50,
        description: "Soft, spongy mini crepes served as a trio with vegetable kurma & chutney.",
      },
      {
        name: "Mysore Masala Dosa",
        category: "Meals",
        originalPrice: 150,
        discountPrice: 75,
        description: "Crispy crepe smeared with spicy red garlic chutney and savory potato mash.",
      },
      {
        name: "Madurai Kari Dosa",
        category: "Meals",
        originalPrice: 220,
        discountPrice: 110,
        description: "3-layered Madurai specialty thick dosa topped with egg and spiced minced meat.",
      },
      {
        name: "Kal Dosa",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Soft & thick traditional griddle-cooked dosa served with chutney.",
      },
      {
        name: "Soft Idli (2 Pcs)",
        category: "Meals",
        originalPrice: 60,
        discountPrice: 30,
        description: "Fluffy steamed rice cakes served hot with vegetable sambar & coriander chutney.",
      },
      {
        name: "Ghee Mini Sambar Idli",
        category: "Meals",
        originalPrice: 110,
        discountPrice: 55,
        description: "Bite-sized mini idlis submerged in hot aromatic sambar topped with pure melted ghee.",
      },
      {
        name: "Kanchipuram Idli",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Spiced steamed idli seasoned with black pepper, ginger & cumin seeds.",
      },
      {
        name: "Idiyappam with Coconut Milk",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Steamed rice string hoppers served with sweet cardamom coconut milk.",
      },
      {
        name: "Medu Vada (2 Pcs)",
        category: "Snacks",
        originalPrice: 60,
        discountPrice: 30,
        description: "Crispy savory fried lentil donuts with crunchy exterior & fluffy center.",
      },
      {
        name: "Paruppu Vada",
        category: "Snacks",
        originalPrice: 50,
        discountPrice: 25,
        description: "Crispy chana dal vada mixed with onions, curry leaves and fennel seeds.",
      },
      {
        name: "Sambar Vada",
        category: "Snacks",
        originalPrice: 80,
        discountPrice: 40,
        description: "Golden crisp medu vadas soaked in hot vegetable sambar.",
      },
      {
        name: "Ven Pongal",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Comforting rice & moong dal porridge tempered with ghee, cashews, cumin & pepper.",
      },
      {
        name: "Rava Upma",
        category: "Meals",
        originalPrice: 60,
        discountPrice: 30,
        description: "Warm roasted semolina breakfast cooked with mustard seeds, lentils & veggies.",
      },
      {
        name: "Onion Uttapam",
        category: "Meals",
        originalPrice: 110,
        discountPrice: 55,
        description: "Thick savory pancake topped with finely chopped onions, chillies & cilantro.",
      },
      {
        name: "Appam with Coconut Milk",
        category: "Meals",
        originalPrice: 100,
        discountPrice: 50,
        description: "Lacy bowl-shaped fermented rice crepe with soft fluffy center served with sweet milk.",
      },
      {
        name: "Egg Appam",
        category: "Meals",
        originalPrice: 120,
        discountPrice: 60,
        description: "Fresh appam cooked with a poached egg baked right in the center.",
      },
      {
        name: "Puttu & Kadala Curry",
        category: "Meals",
        originalPrice: 120,
        discountPrice: 60,
        description: "Layered steamed rice flour cylinder served with spicy black chickpea gravy.",
      },
    ],
  },
  {
    group: "Parotta & Breads",
    items: [
      {
        name: "Flaky Parotta (2 Pcs)",
        category: "Meals",
        originalPrice: 80,
        discountPrice: 40,
        description: "Flaky, multi-layered Tamil style flatbread served with spicy vegetable or meat salna.",
      },
      {
        name: "Malabar Kerala Parotta",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Soft, golden spiral-layered Kerala wheat parotta served with spicy curry.",
      },
      {
        name: "Veg Kothu Parotta",
        category: "Fast Food",
        originalPrice: 130,
        discountPrice: 65,
        description: "Shredded flaky parotta tossed on hot tawa with onions, tomatoes, vegetables & spices.",
      },
      {
        name: "Egg Kothu Parotta",
        category: "Fast Food",
        originalPrice: 160,
        discountPrice: 80,
        description: "Shredded parotta scrambled on hot iron griddle with eggs, onions & savory salna.",
      },
      {
        name: "Chicken Kothu Parotta",
        category: "Fast Food",
        originalPrice: 190,
        discountPrice: 95,
        description: "Shredded parotta tossed with succulent chicken pieces, eggs, and spicy salna gravy.",
      },
      {
        name: "Fresh Chapati (3 Pcs)",
        category: "Meals",
        originalPrice: 70,
        discountPrice: 35,
        description: "Soft whole-wheat chapatis served with vegetable kurma or dal.",
      },
    ],
  },
  {
    group: "Biryani & Rice Specials",
    items: [
      {
        name: "Chicken Biryani",
        category: "Meals",
        originalPrice: 240,
        discountPrice: 120,
        description: "Aromatic Seeraga Samba rice dum biryani with tender chicken pieces & onion raita.",
      },
      {
        name: "Mutton Biryani",
        category: "Meals",
        originalPrice: 320,
        discountPrice: 160,
        description: "Rich authentic mutton biryani cooked with fragrant spices, ghee & boiled egg.",
      },
      {
        name: "Ambur Chicken Biryani",
        category: "Meals",
        originalPrice: 220,
        discountPrice: 110,
        description: "Famous North Arcot style biryani cooked with mild red chilli paste & chicken.",
      },
      {
        name: "Dindigul Thalappakatti Biryani",
        category: "Meals",
        originalPrice: 250,
        discountPrice: 125,
        description: "Signature pepper-infused short-grain rice biryani with rich savory flavor.",
      },
      {
        name: "Thalassery Malabar Biryani",
        category: "Meals",
        originalPrice: 230,
        discountPrice: 115,
        description: "Fragrant Kaima rice biryani topped with fried onions, cashews & raisins.",
      },
      {
        name: "Zesty Lemon Rice",
        category: "Meals",
        originalPrice: 80,
        discountPrice: 40,
        description: "Fragrant turmeric rice tempered with fresh lemon juice, mustard seeds & roasted peanuts.",
      },
      {
        name: "Puliyodarai Tamarind Rice",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Traditional temple-style tangy tamarind spiced rice.",
      },
      {
        name: "Curd Rice (Thayir Sadam)",
        category: "Meals",
        originalPrice: 70,
        discountPrice: 35,
        description: "Cooling seasoned yogurt rice tempered with mustard, pomegranates & curry leaves.",
      },
      {
        name: "Coconut Rice",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Aromatic rice tossed with freshly grated coconut, cashews & green chillies.",
      },
      {
        name: "Spicy Tomato Rice",
        category: "Meals",
        originalPrice: 90,
        discountPrice: 45,
        description: "Flavorful rice cooked with tangy tomatoes, onions, garlic and South Indian spices.",
      },
      {
        name: "Sambar Rice",
        category: "Meals",
        originalPrice: 100,
        discountPrice: 50,
        description: "Comfort meal of rice cooked with lentils, mixed vegetables & aromatic sambar powder.",
      },
      {
        name: "Hot Rasam Rice",
        category: "Meals",
        originalPrice: 80,
        discountPrice: 40,
        description: "Steaming rice paired with pepper-garlic tamarind rasam broth.",
      },
      {
        name: "Bisi Bele Bath",
        category: "Meals",
        originalPrice: 120,
        discountPrice: 60,
        description: "Karnataka special spicy hot lentil-rice dish enriched with ghee & crisp boondi.",
      },
      {
        name: "South Indian Thali Meals",
        category: "Meals",
        originalPrice: 180,
        discountPrice: 90,
        description: "Full banana leaf thali meal with rice, sambar, rasam, kootu, poriyal, appalam & sweet.",
      },
    ],
  },
  {
    group: "Starters & Curries",
    items: [
      {
        name: "Chicken 65",
        category: "Fast Food",
        originalPrice: 180,
        discountPrice: 90,
        description: "Deep-fried spicy chicken morsels marinated in red chilli, curry leaves & lemon.",
      },
      {
        name: "Chicken Chettinad Gravy",
        category: "Meals",
        originalPrice: 220,
        discountPrice: 110,
        description: "Fiery Karaikudi chicken curry cooked with freshly ground whole spices & roasted coconut.",
      },
      {
        name: "Kerala Meen Fish Curry",
        category: "Meals",
        originalPrice: 240,
        discountPrice: 120,
        description: "Tender fish steaks cooked in spiced coconut milk gravy.",
      },
      {
        name: "Kuzhi Paniyaram (6 Pcs)",
        category: "Snacks",
        originalPrice: 80,
        discountPrice: 40,
        description: "Crispy dumplings made in special appe pan served with spicy tomato chutney.",
      },
    ],
  },
  {
    group: "Sweets & Beverages",
    items: [
      {
        name: "Ghee Mysore Pak",
        category: "Desserts",
        originalPrice: 120,
        discountPrice: 60,
        description: "Melt-in-your-mouth traditional sweet made with besan flour, pure ghee and sugar.",
      },
      {
        name: "Sakkarai Sweet Pongal",
        category: "Desserts",
        originalPrice: 90,
        discountPrice: 45,
        description: "Rich sweet rice cooked with organic jaggery, ghee, cashews & cardamom.",
      },
      {
        name: "Semiya Payasam",
        category: "Desserts",
        originalPrice: 80,
        discountPrice: 40,
        description: "Rich vermicelli pudding cooked in condensed milk with cardamom & cashews.",
      },
      {
        name: "Degree Filter Coffee",
        category: "Beverages",
        originalPrice: 40,
        discountPrice: 20,
        description: "Freshly brewed authentic South Indian chicory filter coffee with frothy hot milk.",
      },
    ],
  },
];

// Helper to flatten all items
export const ALL_FOOD_ITEMS = FOOD_CATALOG.flatMap((group) => group.items);
